
import React from "react";

const LegalDisclaimer = () => {
  return (
    <section id="disclaimer" className="pt-20 pb-10 bg-cyber-dark">
      <div className="container mx-auto px-4">
        <div className="glass-card p-6 mb-10">
          <h3 className="text-white font-display font-semibold text-lg mb-4">Legal Disclaimer</h3>
          <div className="text-gray-300 text-sm space-y-3">
            <p>
              Resume & Job Finder AI Suite is an AI-powered tool designed to assist with resume enhancement and job search and is provided "as is" without any warranties, express or implied. While we strive for accuracy and usefulness, AI Web Tools LLC does not guarantee employment outcomes, interview results, or the suitability of content for any particular purpose.
            </p>
            <p>
              Users are solely responsible for reviewing, verifying, and approving all content generated by this tool before submission to potential employers. AI Web Tools LLC shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or in any way connected with the use of this service.
            </p>
            <p>
              By using Resume & Job Finder AI Suite, you acknowledge that employment outcomes are dependent on numerous factors beyond our control, including but not limited to individual qualifications, job market conditions, and employer preferences.
            </p>
            <p>
              For full terms and conditions, please refer to our <a href="https://aiwebtools.ai/terms-of-services" className="text-cyber-primary-purple hover:underline">Terms of Service</a>.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LegalDisclaimer;
