
import React, { useState, useRef, useEffect } from "react";
import { MessageSquare, Send, X, Minimize, Maximize } from "lucide-react";

const SupportChat = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [isMinimized, setIsMinimized] = useState(false);
  const [message, setMessage] = useState("");
  const [chatHistory, setChatHistory] = useState<Array<{ sender: string; text: string; timestamp: Date }>>([
    {
      sender: "bot",
      text: "Hello! I'm the AI Web Tools support assistant. How can I help you with Resume Enhancer GPT today?",
      timestamp: new Date(),
    },
  ]);
  const [isTyping, setIsTyping] = useState(false);
  const chatContainerRef = useRef<HTMLDivElement>(null);

  // Website content knowledge base
  const knowledgeBase = {
    "resume enhancer": [
      "Resume Enhancer GPT helps optimize your resume for specific job applications by analyzing your current resume and suggesting tailored improvements.",
      "The process starts with AI transcribing your complete resume, capturing all details including job history and references.",
      "After transcription, the AI asks about your target job and company to tailor the enhancements specifically for that opportunity.",
      "The AI performs web research on your target position and company to gather insights about requirements, culture, and values."
    ],
    "features": [
      "Our AI accurately transcribes your complete resume, capturing all details including job history, references, and other critical information.",
      "Web research on your target job and company to gather insights about requirements, culture, and values for tailored enhancements.",
      "Expertly expand skills, experiences, and achievements that align with job requirements while preserving your original resume's integrity.",
      "After your approval, we provide a comprehensive rewrite that integrates all enhancements while maintaining your original information.",
      "Get your enhanced resume in a professionally formatted Word document, ready to submit to potential employers.",
      "Receive a perfectly aligned cover letter that complements your enhanced resume and highlights your qualifications for the specific role."
    ],
    "process": [
      "Upload Your Resume: Share your current resume with our AI, which accurately transcribes all existing information without missing any details.",
      "Specify Target Position: Tell us which job and company you're applying to so we can research and tailor enhancements specifically for that opportunity.",
      "Review Suggested Enhancements: Our AI analyzes your resume against job requirements and suggests strategic improvements to highlight relevant skills and experiences.",
      "Approve Changes: Review the suggested enhancements and provide feedback before the AI creates your final enhanced resume.",
      "Download Enhanced Documents: Receive your professionally formatted resume and matching cover letter as downloadable Word documents.",
      "Land More Interviews: Submit your optimized resume to potential employers and increase your chances of getting called for interviews."
    ],
    "tools": [
      "Resume Enhancer GPT: Available at https://chatgpt.com/g/g-SUjFvDzsr-resume-enhancer-gpt",
      "Resume Specialist GPT: Available at https://chatgpt.com/g/g-3RPD1GkR4-resume-specialist-gpt",
      "Job Finder GPT: Available at https://chatgpt.com/g/g-67e1ec8fe9f881918c0b884a43034b9d-job-finder-gpt",
      "More AI tools are available at www.aiwebtools.ai"
    ],
    "contact": [
      "For technical support, you can email us at Contact@ai-webtools.com or call us at (475) 800-8096.",
      "AI Web Tools LLC provides customer support for all our AI-powered tools."
    ],
    "legal": [
      "Resume Enhancer GPT is an AI-powered tool designed to assist with resume enhancement and is provided 'as is' without any warranties, express or implied.",
      "Users are solely responsible for reviewing, verifying, and approving all content generated by this tool before submission to potential employers.",
      "AI Web Tools LLC shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or in any way connected with the use of this service.",
      "For full terms and conditions, please refer to our Terms of Service at https://aiwebtools.ai/terms-of-services"
    ]
  };

  // Function to generate intelligent responses based on user input
  const generateResponse = (userMessage: string) => {
    const normalizedMessage = userMessage.toLowerCase();
    let response = "";

    // Check if the message contains certain keywords and generate appropriate responses
    if (normalizedMessage.includes("resume") && (normalizedMessage.includes("enhance") || normalizedMessage.includes("improvement") || normalizedMessage.includes("optimize"))) {
      response = knowledgeBase["resume enhancer"][Math.floor(Math.random() * knowledgeBase["resume enhancer"].length)];
    } 
    else if (normalizedMessage.includes("feature") || normalizedMessage.includes("what can") || normalizedMessage.includes("capabilities") || normalizedMessage.includes("do for me")) {
      response = knowledgeBase["features"][Math.floor(Math.random() * knowledgeBase["features"].length)];
    }
    else if (normalizedMessage.includes("process") || normalizedMessage.includes("how it works") || normalizedMessage.includes("steps") || normalizedMessage.includes("how do i")) {
      response = knowledgeBase["process"][Math.floor(Math.random() * knowledgeBase["process"].length)];
    }
    else if (normalizedMessage.includes("tool") || normalizedMessage.includes("gpt") || normalizedMessage.includes("ai tools") || normalizedMessage.includes("other tools")) {
      response = knowledgeBase["tools"][Math.floor(Math.random() * knowledgeBase["tools"].length)];
    }
    else if (normalizedMessage.includes("contact") || normalizedMessage.includes("support") || normalizedMessage.includes("help") || normalizedMessage.includes("phone") || normalizedMessage.includes("email")) {
      response = knowledgeBase["contact"][Math.floor(Math.random() * knowledgeBase["contact"].length)];
    }
    else if (normalizedMessage.includes("legal") || normalizedMessage.includes("disclaimer") || normalizedMessage.includes("terms") || normalizedMessage.includes("privacy") || normalizedMessage.includes("liability")) {
      response = knowledgeBase["legal"][Math.floor(Math.random() * knowledgeBase["legal"].length)];
    }
    else if (normalizedMessage.includes("hello") || normalizedMessage.includes("hi") || normalizedMessage.includes("hey")) {
      response = "Hello! I'm the AI Web Tools support assistant. How can I help you with Resume Enhancer GPT today?";
    }
    else if (normalizedMessage.includes("thank")) {
      response = "You're welcome! Is there anything else I can help you with regarding our AI Web Tools?";
    }
    else if (normalizedMessage.includes("cost") || normalizedMessage.includes("price") || normalizedMessage.includes("subscription") || normalizedMessage.includes("pay")) {
      response = "Resume Enhancer GPT is available through ChatGPT. You would need a ChatGPT subscription to access all of our advanced AI tools. Visit https://chatgpt.com/g/g-SUjFvDzsr-resume-enhancer-gpt for more details.";
    }
    else if (normalizedMessage.includes("download") || normalizedMessage.includes("format") || normalizedMessage.includes("file") || normalizedMessage.includes("word")) {
      response = "Your enhanced resume and cover letter will be available for download in a professionally formatted Word document, ready to submit to potential employers.";
    }
    else if (normalizedMessage.includes("cover letter") || normalizedMessage.includes("letter")) {
      response = "Resume Enhancer GPT also creates a customized cover letter that complements your enhanced resume and is specifically tailored to your target position and company.";
    }
    else {
      // Default responses for messages that don't match specific patterns
      const defaultResponses = [
        "Resume Enhancer GPT helps optimize your resume for specific job applications by analyzing your current resume and suggesting tailored improvements.",
        "Our AI tools use advanced natural language processing to create professional, ATS-friendly resumes that highlight your relevant skills and experiences.",
        "For more specific information about our Resume Enhancer GPT, please visit https://chatgpt.com/g/g-SUjFvDzsr-resume-enhancer-gpt or contact us at Contact@ai-webtools.com.",
        "We have multiple AI tools available at www.aiwebtools.ai to help with various career and productivity needs.",
        "Is there anything specific about resume enhancement or our other AI tools that you'd like to know more about?"
      ];
      response = defaultResponses[Math.floor(Math.random() * defaultResponses.length)];
    }

    return response;
  };

  const toggleChat = () => {
    setIsOpen(!isOpen);
    setIsMinimized(false);
  };

  const toggleMinimize = () => {
    setIsMinimized(!isMinimized);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!message.trim()) return;

    // Add user message to chat
    const userMessage = {
      sender: "user",
      text: message,
      timestamp: new Date(),
    };
    setChatHistory((prev) => [...prev, userMessage]);
    setMessage("");

    // Show typing indicator
    setIsTyping(true);

    // Generate AI response with slight delay to simulate thinking
    setTimeout(() => {
      const aiResponse = generateResponse(userMessage.text);
      setChatHistory((prev) => [
        ...prev,
        {
          sender: "bot",
          text: aiResponse,
          timestamp: new Date(),
        },
      ]);
      setIsTyping(false);
    }, 1500);
  };

  // Scroll to bottom of chat when new messages are added
  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [chatHistory, isTyping]);

  return (
    <div className="fixed bottom-6 right-6 z-40">
      {/* Chat Button */}
      <button
        onClick={toggleChat}
        className={`flex items-center justify-center w-14 h-14 rounded-full text-white shadow-neon-glow transition-all ${
          isOpen ? "bg-cyber-primary-purple" : "bg-cyber-neon-blue animate-pulse-glow"
        }`}
        aria-label="Chat Support"
      >
        {isOpen ? <X size={20} /> : <MessageSquare size={20} />}
      </button>

      {/* Chat Window */}
      {isOpen && (
        <div
          className={`absolute bottom-16 right-0 w-80 sm:w-96 transition-all duration-300 transform glass-card border border-white/10 overflow-hidden shadow-lg ${
            isMinimized ? "h-12" : "h-[450px]"
          }`}
        >
          {/* Chat Header */}
          <div className="bg-cyber-primary-purple/20 backdrop-blur-md p-3 flex justify-between items-center border-b border-white/10">
            <div className="flex items-center">
              <div className="w-6 h-6 rounded-full bg-cyber-primary-purple flex items-center justify-center mr-2">
                <MessageSquare size={12} className="text-white" />
              </div>
              <h3 className="text-white text-sm font-medium">AI Web Tools Support</h3>
            </div>
            <div className="flex items-center space-x-2">
              <button 
                onClick={toggleMinimize}
                className="text-white/70 hover:text-white transition-colors"
              >
                {isMinimized ? <Maximize size={14} /> : <Minimize size={14} />}
              </button>
              <button 
                onClick={toggleChat}
                className="text-white/70 hover:text-white transition-colors"
              >
                <X size={14} />
              </button>
            </div>
          </div>

          {!isMinimized && (
            <>
              {/* Chat Messages */}
              <div 
                ref={chatContainerRef}
                className="flex-1 p-4 overflow-y-auto h-[350px] scrollbar-none"
              >
                {chatHistory.map((msg, index) => (
                  <div
                    key={index}
                    className={`mb-3 flex ${msg.sender === "user" ? "justify-end" : "justify-start"}`}
                  >
                    <div
                      className={`max-w-[80%] rounded-lg p-3 ${
                        msg.sender === "user"
                          ? "bg-cyber-primary-purple/30 text-white"
                          : "bg-cyber-dark-purple/60 border border-white/10 text-gray-200"
                      }`}
                    >
                      <p className="text-sm">{msg.text}</p>
                      <p className="text-xs opacity-50 mt-1 text-right">
                        {msg.timestamp.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                      </p>
                    </div>
                  </div>
                ))}
                {isTyping && (
                  <div className="mb-3 flex justify-start">
                    <div className="max-w-[80%] rounded-lg p-3 bg-cyber-dark-purple/60 border border-white/10 text-gray-200">
                      <div className="flex space-x-1">
                        <div className="w-2 h-2 rounded-full bg-cyber-primary-purple/70 animate-bounce" style={{ animationDelay: "0ms" }}></div>
                        <div className="w-2 h-2 rounded-full bg-cyber-primary-purple/70 animate-bounce" style={{ animationDelay: "150ms" }}></div>
                        <div className="w-2 h-2 rounded-full bg-cyber-primary-purple/70 animate-bounce" style={{ animationDelay: "300ms" }}></div>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Chat Input */}
              <div className="p-3 border-t border-white/10">
                <form onSubmit={handleSubmit} className="flex gap-2">
                  <input
                    type="text"
                    value={message}
                    onChange={(e) => setMessage(e.target.value)}
                    placeholder="Type your message..."
                    className="flex-1 bg-cyber-dark/50 border border-white/10 rounded-md px-3 py-2 text-sm text-white focus:outline-none focus:ring-1 focus:ring-cyber-primary-purple"
                  />
                  <button
                    type="submit"
                    className="bg-cyber-primary-purple text-white p-2 rounded-md hover:bg-cyber-secondary-purple transition-colors"
                    disabled={!message.trim()}
                  >
                    <Send size={18} />
                  </button>
                </form>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
};

export default SupportChat;
